//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaction
    {
        [Required(ErrorMessage = "*")]
        public int TransactionID { get; set; }
        [Required(ErrorMessage = "*")]
        public int SenderAccountID { get; set; }
        [Required(ErrorMessage = "*")]
        public int ReceiverAccountID { get; set; }
        [Required(ErrorMessage = "*")]
        public string MobileNo { get; set; }
        [Required(ErrorMessage = "*")]
        public int Amount { get; set; }
        [Required(ErrorMessage = "*")]
        public string TransactionType { get; set; }
        [Required(ErrorMessage = "*")]
        public string Remark { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
